# Generated by Django 5.2.13 on 2026-05-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_classificacao_pessoa_movimentocontas_parcelacontas'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='classificacoes',
            field=models.ManyToManyField(blank=True, related_name='movimentos_vinculados', to='invoices.classificacao'),
        ),
        migrations.AddField(
            model_name='parcelacontas',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='classificacao',
            name='tipo',
            field=models.CharField(choices=[('DESPESA', 'Despesa'), ('RECEITA', 'Receita')], max_length=32),
        ),
        migrations.AlterField(
            model_name='movimentocontas',
            name='tipo',
            field=models.CharField(choices=[('APAGAR', 'A Pagar'), ('ARECEBER', 'A Receber')], default='APAGAR', max_length=16),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(choices=[('CLIENTE-FORNECEDOR', 'Cliente-Fornecedor'), ('FORNECEDOR', 'Fornecedor'), ('CLIENTE', 'Cliente'), ('FATURADO', 'Faturado')], max_length=32),
        ),
    ]
